### PR TITLE
Use eventemitter3 and inherits instead of events and util

### PR DESCRIPTION
**Pull request by mridgway**
Should save some kb

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
How much does it save?

**Comment by koulmomo** [comment]
@mridgway scary name aside, do you know what the changed behavior is with regards to [`setMaxListeners`](https://github.com/primus/eventemitter3#eventemitter3)?

regular `EventEmitter` sets a default max number of listeners to 10 and prints warnings when you go above (which is great in helping you find memory-leaks) but still lets you override the default in case you really do need more than 10 listeners. 

current behavior [here](https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n)

**Comment by mridgway** [comment]
> How much does it save?

Uncompressed, the dispatchr utils go from 33.5kb to 13.3kb. Compress: 12.3kb -> 4.23kb.

> do you know what the changed behavior is with regards to setMaxListeners?

On the server since the stores are shortlived, we wouldn't ever really see max listeners hit unless there were a large number of components that attached themselves, which isn't really a memory leak.

On the client, it would indeed be more difficult to debug memory leaks where the listeners were not unregistered on `componentWillUnmount`. But, eventemitter also tends to give a lot of false positives with larger applications anyway.

**Comment by redonkulus** [comment]
:shipit:

**Comment by Vijar** [comment]
:boat:

**Pull request merged**
